services:
  autonomous:
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: "${HOST_UID:-1000}"
        USER_GID: "${HOST_GID:-1000}"

    network_mode: host
    ipc: host

    gpus: all

    environment:
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-0}"
      ROS_LOCALHOST_ONLY: "0"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp

    stdin_open: true
    tty: true

    volumes:
      - .:/workspace

    working_dir: /workspace

    command: sleep infinity
